name: CI
# Define em que eventos o workflow será acionado (ex: push para a branch main)
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
