name: CI
# Define em que eventos o workflow será acionado (ex: push para a branch main)
on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install

